function initializeAnswers() {
    if (typeof (localStorage.answers) == 'undefined') {
        console.log('load blank')
        return [
            { 'questionNumber': 1, 'value': '-3' },
            { 'questionNumber': 2, 'value': '-3' },
            { 'questionNumber': 3, 'value': '-3' },
            { 'questionNumber': 4, 'value': '-3' },
            { 'questionNumber': 5, 'value': '-3' },
            { 'questionNumber': 6, 'value': '-3' },
            { 'questionNumber': 7, 'value': '-3' },
            { 'questionNumber': 8, 'value': '-3' },
            { 'questionNumber': 9, 'value': '-3' },
            { 'questionNumber': 10, 'value': '-3' },
            { 'questionNumber': 11, 'value': '-3' },
            { 'questionNumber': 12, 'value': '' },
            { 'questionNumber': 13, 'value': '-3' },
            { 'questionNumber': 14, 'value': '-3' },
            { 'questionNumber': 15, 'value': '-3' },
            { 'questionNumber': 16, 'value': '-3' },
            { 'questionNumber': 17, 'value': '-3' },
            { 'questionNumber': 18, 'value': '-3' },
            { 'questionNumber': 19, 'value': '-3' },
            { 'questionNumber': 20, 'value': '-3' },
            { 'questionNumber': 21, 'value': '-3' },
            { 'questionNumber': 22, 'value': '-3' },
            { 'questionNumber': 23, 'value': '-3' },
            { 'questionNumber': 24, 'value': '-3' },
            { 'questionNumber': 25, 'value': '-3' },
            { 'questionNumber': 26, 'value': '-3' },
            { 'questionNumber': 27, 'value': '-3' },
            { 'questionNumber': 28, 'value': '-3' },
            { 'questionNumber': 29, 'value': '-3' },
            { 'questionNumber': 30, 'value': '-3' },
            { 'questionNumber': 31, 'value': '-3' },
            { 'questionNumber': 32, 'value': '-3' },
            { 'questionNumber': 33, 'value': '-3' },
            { 'questionNumber': 34, 'value': '-3' },
            { 'questionNumber': 35, 'value': '-3' },
            { 'questionNumber': 36, 'value': '-3' },
            { 'questionNumber': 37, 'value': '-3' },
            { 'questionNumber': 38, 'value': '-3' },
            { 'questionNumber': 39, 'value': '-3' },
            { 'questionNumber': 40, 'value': '-3' },
            { 'questionNumber': 41, 'value': '-3' },
            { 'questionNumber': 42, 'value': '-3' },
            { 'questionNumber': 43, 'value': '-3' },
            { 'questionNumber': 44, 'value': '-3' },
        ]
    }
    else {
        console.log('load from localstorage')
        return JSON.parse(localStorage.getItem("answers"));
    }
}

let answers = initializeAnswers()
function setBlank() {
    localStorage.personName = ''
    answers = [
        { 'questionNumber': 1, 'value': '-3' },
            { 'questionNumber': 2, 'value': '-3' },
            { 'questionNumber': 3, 'value': '-3' },
            { 'questionNumber': 4, 'value': '-3' },
            { 'questionNumber': 5, 'value': '-3' },
            { 'questionNumber': 6, 'value': '-3' },
            { 'questionNumber': 7, 'value': '-3' },
            { 'questionNumber': 8, 'value': '-3' },
            { 'questionNumber': 9, 'value': '-3' },
            { 'questionNumber': 10, 'value': '-3' },
            { 'questionNumber': 11, 'value': '-3' },
            { 'questionNumber': 12, 'value': '' },
            { 'questionNumber': 13, 'value': '-3' },
            { 'questionNumber': 14, 'value': '-3' },
            { 'questionNumber': 15, 'value': '-3' },
            { 'questionNumber': 16, 'value': '-3' },
            { 'questionNumber': 17, 'value': '-3' },
            { 'questionNumber': 18, 'value': '-3' },
            { 'questionNumber': 19, 'value': '-3' },
            { 'questionNumber': 20, 'value': '-3' },
            { 'questionNumber': 21, 'value': '-3' },
            { 'questionNumber': 22, 'value': '-3' },
            { 'questionNumber': 23, 'value': '-3' },
            { 'questionNumber': 24, 'value': '-3' },
            { 'questionNumber': 25, 'value': '-3' },
            { 'questionNumber': 26, 'value': '-3' },
            { 'questionNumber': 27, 'value': '-3' },
            { 'questionNumber': 28, 'value': '-3' },
            { 'questionNumber': 29, 'value': '-3' },
            { 'questionNumber': 30, 'value': '-3' },
            { 'questionNumber': 31, 'value': '-3' },
            { 'questionNumber': 32, 'value': '-3' },
            { 'questionNumber': 33, 'value': '-3' },
            { 'questionNumber': 34, 'value': '-3' },
            { 'questionNumber': 35, 'value': '-3' },
            { 'questionNumber': 36, 'value': '-3' },
            { 'questionNumber': 37, 'value': '-3' },
            { 'questionNumber': 38, 'value': '-3' },
            { 'questionNumber': 39, 'value': '-3' },
            { 'questionNumber': 40, 'value': '-3' },
            { 'questionNumber': 41, 'value': '-3' },
            { 'questionNumber': 42, 'value': '-3' },
            { 'questionNumber': 43, 'value': '-3' },
            { 'questionNumber': 44, 'value': '-3' },
    ]
}